baseURL = "https://dongheon-dev.github.io/reviewlog/"
languageCode = "ko-kr"
title = "Re:View,Log"
theme = "stack"

[pagination]
  pagerSize = 10

[params]
  mainSections = ["post"]
  
[params.sidebar]
  subtitle = "re view, review, log"

[taxonomies]
  category = "categories"
  tag = "tags"

[params.widgets]

[[params.widgets.homepage]]
  type = "search"

[[params.widgets.homepage]]
  type = "archives"

[[params.widgets.homepage]]
  type = "categories"

[[params.widgets.homepage]]
  type = "tag-cloud"

[markup.goldmark.renderer]
  unsafe = true

[[params.widgets.page]]
  type = "search"

[[params.widgets.page]]
  type = "archives"

[[params.widgets.page]]
  type = "categories"

[[params.widgets.page]]
  type = "tag-cloud"